name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: Platane/snk@v3
        with:
          github_user_name: raphaelucena97
          outputs: |
            dist/github-snake.svg
            dist/github-snake.gif

      - name: Commit & Push files
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add dist/
          git commit -m "generate contribution snake" || echo "No changes to commit"
          git push

      - uses: actions/upload-artifact@v4
        with:
          name: snake
          path: dist
